import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "@/redux/provider";
import { ToastProvider } from "@/components/providers/toaster-provider";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        {/* ✅ Load Geist and Geist Mono via Google Fonts CDN */}
        <link
          href="https://fonts.googleapis.com/css2?family=Geist&family=Geist+Mono&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className="font-sans antialiased">
        <ReduxProvider>
          <ToastProvider />
          <Toaster />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
